### PR TITLE
use new fact easyrsa to configure easyrsa 2 or 3

### LINKED ISSUE #269: Epel has upgraded `easy-rsa` to version 3.x and removed 2.x, breaking the module
## Affected Puppet, Ruby, OS and module versions/distributions
N/A (At least epel for EL7)

## What are you seeing
`easy-rsa` 3.x has a completely different way of working to version 2.x and so the commands in the module fail to work (`pkitool` for example).
It seems the commands have been rolled into the `easyrsa`  script supplied, but the commands don't seem to quite map 1-2-1 with the original structure of 2.x.

### PR DESCRIPTION
**Pull request by Dan33l**
#### Pull Request (PR) description

A rework of PR #278 

#### This Pull Request (PR) fixes the following issues

Fixes #269

### CODE REVIEW

File: lib/facter/easyrsa.rb [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+      when /8|9|16.04|18.04/
+        binaryv2 = '/usr/share/easy-rsa/pkitool'
+        binaryv3 = '/usr/share/easy-rsa/easyrsa'
+      else
+        binaryv2 = '/usr/share/doc/openvpn/examples/easy-rsa/2.0/pkitool'
+        binaryv3 = '/usr/share/doc/openvpn/examples/easy-rsa/3.0/easyrsa'
+      end
+    when /Archlinux/
+      binaryv2 = '/usr/share/easy-rsa/2.0/pkitool'
+      binaryv3 = '/usr/share/easy-rsa/3/easyrsa'
```
Comment (bastelfreak) [inline lib/facter/easyrsa.rb]: `/usr/bin/easyrsa` is the correct path

File: lib/facter/easyrsa.rb [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+    when /Amazon/
+      binaryv2 = '/usr/share/easy-rsa/2.0/pkitool'
+      binaryv3 = '/usr/share/easy-rsa/3/easyrsa'
+    when /FreeBSD/
+      binaryv2 = '/usr/local/share/easy-rsa/pkitool'
+      binaryv3 = '/usr/local/share/easy-rsa/easyrsa'
+    end
+
+    if File.exist? binaryv2
+      Open3.popen2("#{binaryv2} --help") do |stdin, stdout, status_thread|
```
Comment (bastelfreak) [inline lib/facter/easyrsa.rb]: Puppet has some tooling to check if a binary is within `$PATH` and can also execute it:
https://github.com/voxpupuli/puppet-rabbitmq/blob/d6a216f985e421e81ac3e66dcfcd59faaada9da1/lib/facter/erl_ssl_path.rb#L7-L8

File: lib/facter/easyrsa.rb [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+        stdout.each_line do |line|
+          if line.include?('pkitool 2.0')
+            version = '2.0'
+            break
+          end
+        end
+      end
+      version
+    elsif File.exist? binaryv3
```
Comment (bastelfreak) [inline lib/facter/easyrsa.rb]: if both files aren't available, we should check if it is within the `$PATH`

File: manifests/ca.pp [hunk 4]
```diff
@@ -124,86 +131,158 @@
...
-    require => Exec["copy easy-rsa to openvpn config folder ${name}"],
+    require => File["${etc_directory}/openvpn/${name}/easy-rsa"],
   }
 
-  file { "${etc_directory}/openvpn/${name}/easy-rsa/vars":
-    ensure  => file,
-    mode    => '0550',
-    content => template('openvpn/vars.erb'),
-    require => Exec["copy easy-rsa to openvpn config folder ${name}"],
+  if $easyrsa_version == '2.0' {
```
Comment (bastelfreak) [inline manifests/ca.pp]: should we use[ versioncmp()](https://puppet.com/docs/puppet/5.5/function.html#versioncmp) here?

File: manifests/ca.pp [hunk 5]
```diff
@@ -124,86 +131,158 @@
...
+      ensure  => file,
+      mode    => '0550',
+      content => template('openvpn/vars.erb'),
+      require => File["${etc_directory}/openvpn/${name}/easy-rsa"],
+    }
+  } else {
+    file { "${etc_directory}/openvpn/${name}/easy-rsa/vars":
+      ensure  => file,
+      mode    => '0550',
+      content => epp('openvpn/vars-30.epp',
```
Comment (bastelfreak) [inline manifests/ca.pp]: yey epp with params \o/

File: manifests/params.pp [hunk 6]
```diff
@@ -142,11 +151,13 @@
...
       $easyrsa_source      = '/usr/local/share/easy-rsa'
+      $default_easyrsa_ver = '2.0'
       $namespecific_rclink = true
       $systemd             = false
     }
     default: {
       fail("Not supported OS family ${::osfamily}")
     }
   }
+
```
Comment (bastelfreak) [inline manifests/params.pp]: is this newline on purpose?

File: spec/spec_helper_acceptance.rb [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+install_module_dependencies
+
+RSpec.configure do |c|
+
+  # Configure all nodes in nodeset
+  c.before :suite do
+    hosts.each do |host|
+      case host[:platform]
+      when /debian-7-amd64|debian-8-amd64|ubuntu-16.04-amd64/
+        on host, puppet('module', 'install', 'puppetlabs-apt')
```
Comment (bastelfreak) [inline spec/spec_helper_acceptance.rb]: you can do something like this:
```ruby
install_module_from_forge('puppetlabs-apt', '>= 4.1.0 < 7.0.0') if fact('os.family') == 'Debian'
```

File: spec/spec_helper_acceptance.rb [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+        pp = <<-EOS
+        package { 'netcat-openbsd' :
```
Comment (bastelfreak) [inline spec/spec_helper_acceptance.rb]: you can install packages like this:
```ruby
install_package(host, 'netcat-openbsd') if fact('os.release.major')
```

File: templates/server.erb [hunk 9]
```diff
@@ -26,11 +26,21 @@ dh <%= @extca_dh_file %>
 crl-verify <%= @extca_ca_crl_file %>
 <%   end -%>
 <% else -%>
+<%- if scope.lookupvar('::openvpn::params::easyrsa_ver') == '2.0' -%>
```
Comment (bastelfreak) [inline templates/server.erb]: please use ```@openvpn::params::easyrsa_ver``` to access variables (or if you are interested you can turn this into an epp template, but that sould probably done in another PR).

File: templates/vars-30.epp [hunk 10]
```diff
@@ -0,0 +1,80 @@
+# easy-rsa parameter settings
```
Comment (bastelfreak) [inline templates/vars-30.epp]: does this actually need to be a template? Can't we use the files distributed by the operatingsystems?

File: lib/facter/easyrsa.rb (hunk 1 above)
Comment (Dan33l) [reply lib/facter/easyrsa.rb]: For any version of easyrsa ?

File: manifests/ca.pp (hunk 4 above)
Comment (Dan33l) [reply manifests/ca.pp]: I tryed to KISS. To use the function `versioncmp()` is some time usefull. But here, in my opinion it will not provide better result. But i'll do as you prefer. Tell me.

File: manifests/params.pp (hunk 6 above)
Comment (Dan33l) [reply manifests/params.pp]: typo.

File: templates/server.erb (hunk 9 above)
Comment (Dan33l) [reply templates/server.erb]: I need to modify this, so it will be handled.

File: templates/vars-30.epp (hunk 10 above)
Comment (Dan33l) [reply templates/vars-30.epp]: For me, template usage is still relevant because the file `vars` need to be customized for each `openvpn` tunnel.

If you are thinking about something else. Please tell me more.

File: spec/spec_helper_acceptance.rb (hunk 8 above)
Comment (Dan33l) [reply spec/spec_helper_acceptance.rb]: `netcat` was used in a previous version of tests. But now it is not. I'll remove this.

File: spec/spec_helper_acceptance.rb (hunk 7 above)
Comment (Dan33l) [reply spec/spec_helper_acceptance.rb]: I'll use function for `epel` module.
And this  comment makes me realize that `Debian` family OSes does not need special apt sources.

File: lib/facter/easyrsa.rb (hunk 1 above)
Comment (bastelfreak) [reply lib/facter/easyrsa.rb]: for v3. v2 does not exist on Arch Linux.

File: templates/vars-30.epp (hunk 10 above)
Comment (bastelfreak) [reply templates/vars-30.epp]: ah okay. Than it makes sense.

File: lib/facter/easyrsa.rb (hunk 2 above)
Comment (Dan33l) [reply lib/facter/easyrsa.rb]: Nice. Will be used.

File: lib/facter/easyrsa.rb (hunk 3 above)
Comment (Dan33l) [reply lib/facter/easyrsa.rb]: I agree. Will be handled.

**Comment by Dan33l** [comment]
Comments from @bastelfreak's first review are handled.

If you run acceptance tests you will show that 2 runs are needed to make all actions.
This is due to : 
  * `exec` creates certificates for server and clients in `keys` directory as `root`. and so files are owned by `root.root`.
  * a `file` resource is used to make a copy fom `easyrsa` path to `openvpn` instance.
  * some default settings are defined https://github.com/Dan33l/puppet-openvpn/blob/add-easyrsa-3/manifests/ca.pp#L116

I tried to add `notify` to `exec` by i meet a dependency cycle.
Advice to fix this is welcome.

File: lib/facter/easyrsa.rb [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+      end
+    when %r{Amazon}
+      binaryv2 = '/usr/share/easy-rsa/2.0/pkitool'
+      binaryv3 = '/usr/share/easy-rsa/3/easyrsa'
+    when %r{FreeBSD}
+      binaryv2 = '/usr/local/share/easy-rsa/pkitool'
+      binaryv3 = '/usr/local/share/easy-rsa/easyrsa'
+    end
+
+    if File.exist? binaryv2
```
Comment (bastelfreak) [inline lib/facter/easyrsa.rb]: should we flip the logic here? v2 wil be used, even if v3 is available. Shouldn't we always use the latest available version?

File: manifests/params.pp [hunk 12]
```diff
@@ -142,11 +151,17 @@
...
       $namespecific_rclink = true
       $systemd             = false
     }
     default: {
       fail("Not supported OS family ${::osfamily}")
     }
   }
+  $easyrsa_version = $facts['easyrsa'] ? {
+    undef   => $default_easyrsa_ver,
+    ''      => $default_easyrsa_ver,
```
Comment (bastelfreak) [inline manifests/params.pp]: the fact should be reworked to only be undef or return a string.

File: manifests/client.pp [hunk 13]
```diff
@@ -347,6 +374,13 @@
     ],
   }
 
+  file { "${etc_directory}/openvpn/${server}/download-configs/${name}.tar.gz":
+    ensure  => present,
+    replace => 'no',
+    content => "not yet created\n",
```
Comment (bastelfreak) [inline manifests/client.pp]: why is there a content attribute for a .tar.gz file?

File: spec/spec_helper_acceptance.rb [hunk 14]
```diff
@@ -0,0 +1,20 @@
+require 'beaker-rspec'
+require 'beaker-puppet'
+require 'beaker/puppet_install_helper'
+require 'beaker/module_install_helper'
+
+run_puppet_install_helper unless ENV['BEAKER_provision'] == 'no'
```
Comment (bastelfreak) [inline spec/spec_helper_acceptance.rb]: do the acceptance tests also work with docker? If so, we should enable them for travis.

File: lib/facter/easyrsa.rb (hunk 11 above)
Comment (Dan33l) [reply lib/facter/easyrsa.rb]: Ooooooh yes !

File: manifests/params.pp (hunk 12 above)
Comment (Dan33l) [reply manifests/params.pp]: done

File: manifests/client.pp (hunk 13 above)
Comment (Dan33l) [reply manifests/client.pp]: It works also without. I wanted to have the possibility to know if something was wrong with content of file.

content removed.

File: spec/spec_helper_acceptance.rb (hunk 14 above)
Comment (Dan33l) [reply spec/spec_helper_acceptance.rb]: Yes it works with docker.

**Comment by bastelfreak** [comment]
Thanks @Dan33l !
